INSERT INTO INSURER_DETAIL VALUES(1,10,3000,'STAR INSURANCE','Health Plan');
INSERT INTO INSURER_DETAIL VALUES(2,10,1450,'LIC INSURANCE','Family Plan');
INSERT INTO INSURER_DETAIL VALUES(3,10,850,'HDFC INSURANCE','Platinum package');
INSERT INTO INSURER_DETAIL VALUES(4,10,1300,'AXIS HEALTH INSURANCE','Gold Plan');